apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo-container
        image: watri/demo:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
spec:
  type: NodePort
  selector:
    app: app-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001